@baseUrl = http://localhost:3000
@daenerysUserId = 38b4426d-f0d7-409a-bff2-1ae873e2b551
@projectName = the-stark-project

GET {{ baseUrl }}/projects

###

GET {{ baseUrl }}/devboxes

###
## Daenerys devboxes

###
## Get the user id using Microsoft Graph API

GET https://graph.microsoft.com/v1.0/me
Authorization: Bearer {{$aadV2Token}}

###

GET {{ baseUrl }}/devboxes/{{daenerysUserId}}


###
# Get pools for a project
GET {{ baseUrl }}/projects/{{projectName}}/pools


###

## Create a new devbox for Daenerys using /devboxes/:projectName/:userId'
# # @prompt projectName
POST {{ baseUrl }}/devboxes/{{projectName}}/{{daenerysUserId}}
