name: cosmosdb-environment
summary: Creates a CosmosDB using Terraform
description: Deploys an environment using Terraform containing a CosmosDB
runner: "dragonstoneacr.azurecr.io/ade:latest"
templatePath: main.tf
parameters:
  - id: "resource_name"
    name: "Resource Name"
    required: true
    type: "string"
  - id: "location"
    name: "Location"
    required: true
    type: "string"
