name: Markdown Lint

on: [push, pull_request]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.4
      with:
        node-version: '20'
    - name: Install markdownlint-cli
      run: npm install -g markdownlint-cli
    - name: Run markdownlint
      run: markdownlint '**/*.md' --ignore node_modules
